//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using FriendshipFirst.Model;
namespace FriendshipFirst.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendshipFirstContext : DbContext
    {
        public FriendshipFirstContext()
            : base("name=FriendshipFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FF_User> ff_user { get; set; }
        public virtual DbSet<HS_ErrRec> hs_errrec { get; set; }
        public virtual DbSet<HS_DataExchange> hs_dataexchange { get; set; }
        public virtual DbSet<HS_SystemConfig> hs_systemconfig { get; set; }
        public virtual DbSet<HS_GameTable> hs_gametable { get; set; }
        public virtual DbSet<FF_Game> ff_game { get; set; }
        public virtual DbSet<FF_GameRecord> ff_gamerecord { get; set; }
    }
}
